### ISSUE TITLE
Hey Jeremy. Trying to get a hold of you

### ISSUE THREAD

**Issue by phillijw** [jeremy-sylvis/2019-advent-code#1]
Just wanted to let you know that your home frigate site is crawled by google and is fully accessible at the moment. Sorry I couldn't really find a better way to contact you. Tried adding you on discord though

**Comment by jeremy-sylvis** [comment]
@phillijw I saw the discord add and just assumed it was spam - thanks for the heads-up, it's appreciated. I'm applying a basic IP filter for now. I was pretty sure I'd had that subnetted off but clearly misunderstood something and will have to revisit.

**Comment by jeremy-sylvis** [comment]
Okay, applied - it seems to be inaccessible from off-network.

If you're ever in Des Moines, I owe you a beer.
